if state_get("start_cutscene_seen") {
    instance_destroy()
    instance_activate_object(inst_15D031D5_1)
    exit
}

global.party_names = ["kris"]

trigger_code = function() {
	
	
	var black = instance_create(obj_screen_hider, 0, 0, -10000)
	audio_play(snd_noise)
    cutscene_create()
    cutscene_player_canmove(false)
    cutscene_party_follow(false)
    cutscene_set_variable(o_camera, "target", noone)
    cutscene_func(music_fade, [0, 0])
	cutscene_sleep(120)
	
	cutscene_dialogue("* You feel your body waking up.",, false)
    cutscene_wait_dialogue_finish()
	cutscene_sleep(120)

	cutscene_dialogue("* As the world crumbles, you feel a literal wave of nostalgia wash by...",, false)
    cutscene_wait_dialogue_finish()
	cutscene_sleep(120)

	cutscene_dialogue("{char(asriel, 0)}* Dess! Dess! See what I brought!",, false)
    cutscene_wait_dialogue_finish()
	cutscene_sleep(10)

	cutscene_dialogue("{char(dess, 0)}* What is it this time Azzy?",, false)
    cutscene_wait_dialogue_finish()
	cutscene_sleep(10)

	cutscene_dialogue("{char(asriel, 0)}* Ok. I know my last few ideas did not work. And your batsword-",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(dess, 0)} Black. {s(20)} Shard. {s(20)} Blade.",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(asriel, 0)}* your black shard blade is way too strong and hurts a LOT.",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(asriel, 0)}* So I think finally found something that turns into good armor.",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(dess, 0)}* What about the christmas jumper Carol got you lmao.",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(asriel, 0)}* It looks too cringe I don't want to look like a christmas tree.",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(dess, 0)}* Said the jolliest guy I know.",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(asriel, 0)}* Desssssssss, please I actually have something cooool.",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(dess, 0)}* Ok ok, I am not going to interrupt.",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(asriel, 0)}* Ok so, you remember the really cool poster that was in Mr Boom's class.",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(dess, 0)}* You didn't.",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(asriel, 0)}* I did.",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(dess, 0)}* Well, where is it? Show me, show me show me!",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(asriel, 0)}* Ok ok ok. {s(30)} Lo and behold! It turned into this awesome cape!",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(dess, 0)}* Yooooo, that's so badass! {sleep(120)} It looks tough too.",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(dess, 0)}* I am impressed Azzy",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(dess, 0)}* I thought after \"God of Hyperdeath\" you'd be unable to make something cool.",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(asriel, 0)}* You'll learn one day everything about me is cool.",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(dess, 0)}* I am also surprised, I thought the poster would be a darkner? But I guess you never know.",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(asriel, 0)}* What do you think I should call it?",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(dess, 0)}* What name did YOU have for it.",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(asriel, 0)}* What do you mean?",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(dess, 0)}* Come on Azzy I know you already had a name picked out for it.",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(asriel, 0)}* uhm, Penmasters Cloak? Because it's kind of a cloak and it's made by Mr. Boom?",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(dess, 0)}* Fahaha! You know what Azzy that's honestly pretty good, in your standards of course",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(asriel, 0)}* Oh yeah? What would YOU have called it then?",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{char(dess, 0)}* Hm... {sleep(30)} What about",, false)
	cutscene_wait_dialogue_finish()
	cutscene_dialogue("{col(c_orange)}* The Shadow Mantle",, false)
	cutscene_wait_dialogue_finish()
	
    cutscene_sleep(300)
    cutscene_func(function(inst) {
		with(all) { persistent = false }
		instance_destroy(obj_screen_hider)
		game_restart()
    }, [id])
    cutscene_play()
}